input_size: 64
output_size: 256
scale_factor: 4

pre_upsample: false

max_epoch: 200
batch_size: 16
learning_rate: 0.001
loss_fn: "MSE"

use_pretrained: true
pretrained_path: "pretrained/BSRN.pth"
use_checkpoint: false
checkpoint_path: "checkpoint/BSRN.pth"