input_size: 64
output_size: 256

conv1_kernel_size: 9
conv2_kernel_size: 5
conv3_kernel_size: 5

max_epoch: 10
batch_size: 64
learning_rate: 0.0001
loss_fn: "MSE"

use_pretrained: false
pretrained_path: ""
use_checkpoint: true
checkpoint_path: "checkpoint/SRCNN.pth"

